<?php
/**
 * Created by PhpStorm.
 * User: aleksandrcerkasov
 * Date: 17.05.17
 * Time: 22:26
 */

namespace app\controllers;
use Yii;
use app\models\TestForm;

class PostController extends AppController
{
    public $layout = 'basic';

    public function beforeAction($action)
    {
        if ($action->id == 'index') {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        if (Yii::$app->request->isAjax) {
            debug(Yii::$app->request->post());
            return 'test';
        }

        $model = new TestForm();
        if($model->load(Yii::$app->request->post()) ) {
           // debug(Yii::$app->request->post());
           // die;
            if( $model->validate() ) {
                Yii::$app->session->setFlash('success', 'Данные приняты');
            }else{
                Yii::$app->session->setFlash('error', 'Ошибка');
            }
        }
        $this->view->title = 'Все статьи';
        return $this->render('test', compact('model'));
    }

    public function actionShow()
    {
        $this->view->title = 'Одна статья';
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'ключевики...']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'описание страницы...']);
        return $this->render('show');
    }
}